/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logika.Kontroler;
import model.Zakon;
import tabele.TabelaZakon;

/**
 *
 * @author Ana
 */
public class FormaZakon extends javax.swing.JFrame {

    /**
     * Creates new form FormaZakon
     */
    public FormaZakon() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblZakon = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnPregledClanova = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zakon");

        tblZakon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblZakon);

        btnDodaj.setText("Dodaj zakon");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni zakon");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi zakon");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnPregledClanova.setText("Pregled clanova");
        btnPregledClanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledClanovaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addGap(67, 67, 67)
                        .addComponent(btnIzmeni)
                        .addGap(43, 43, 43)
                        .addComponent(btnObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btnPregledClanova)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi)
                    .addComponent(btnPregledClanova))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if(tblZakon.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Potrebno je da izaberete zakon koji zelite da obrisete", "Greska!", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                Zakon z=((TabelaZakon)tblZakon.getModel()).getSelectedObject(tblZakon.getSelectedRow());
                Kontroler.getInstanca().delete(z);
                JOptionPane.showMessageDialog(this, "Uspesno ste obrisali zakon!");
                refreshTbl();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greska prilikom brisanja zakona", "Greska!", JOptionPane.ERROR_MESSAGE);
            } 
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
       
        try {
            List<Zakon> listaZkn=Kontroler.getInstanca().listaZakona();
            
            int brojZakona=1;
            for (Zakon z : listaZkn) {
                brojZakona=Integer.max(1, z.getZakonID());
                
            }
            Zakon z=new Zakon();
            FormaZakonDodaj fzd=new FormaZakonDodaj(this,true,z,"INSERT", brojZakona);
            fzd.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FormaZakon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if(tblZakon.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Potrebno je da izaberete zakon koji zelite da izmenite", "Greska!", JOptionPane.ERROR_MESSAGE);
        }else{
            Zakon z=((TabelaZakon)tblZakon.getModel()).getSelectedObject(tblZakon.getSelectedRow());
            FormaZakonDodaj fzd=new FormaZakonDodaj(this,true,z,"UPDATE",0);
            fzd.setVisible(true);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPregledClanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledClanovaActionPerformed
        if(tblZakon.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Potrebno je da izaberete zakon za koji zelite da vidite clanove", "Greska!", JOptionPane.ERROR_MESSAGE);
        }else{
            Zakon z =((TabelaZakon)tblZakon.getModel()).getSelectedObject(tblZakon.getSelectedRow());
            FormaClan fc=new FormaClan(z);
            fc.setVisible(true);
            
        }
    }//GEN-LAST:event_btnPregledClanovaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaZakon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaZakon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaZakon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaZakon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaZakon().setVisible(true);
            }
        });
    }
    
    public void refreshTbl(){
        List<Zakon> shownZ=loadObjects();
        TabelaZakon tbl=(TabelaZakon) tblZakon.getModel();
        tbl.setList(shownZ);
        tbl.fireTableDataChanged();
    }

    private List<Zakon> loadObjects() {
        try {
            return Kontroler.getInstanca().listaZakona();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPregledClanova;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblZakon;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        try {
            List<Zakon> listaZakona=Kontroler.getInstanca().listaZakona();
            TabelaZakon tblZk=new TabelaZakon(listaZakona);
            tblZakon.setModel(tblZk);
        } catch (Exception ex) {
            Logger.getLogger(FormaArtikal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
