/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logika.Kontroler;
import model.Dobavljac;
import tabele.TabelaDobavljac;

/**
 *
 * @author Ana
 */
public class FormaDobavljac extends javax.swing.JFrame {

    /**
     * Creates new form FormaDobavljac
     */
    public FormaDobavljac() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDobavljac = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dobavljac");

        tblDobavljac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDobavljac);

        btnDodaj.setText("Dodaj dobavljaca");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni dobavljaca");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi dobavljaca");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnDodaj)
                .addGap(70, 70, 70)
                .addComponent(btnIzmeni)
                .addGap(81, 81, 81)
                .addComponent(btnObrisi)
                .addGap(0, 413, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Dobavljac d=new Dobavljac();
        FormaDobavljacDodaj fdd=new FormaDobavljacDodaj(this,true,d,"INSERT");
        fdd.setVisible(true);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if(tblDobavljac.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Potrebno je da izaberete dobavljaca kog zelite da izmenite", "Greska!", JOptionPane.ERROR_MESSAGE);
        }else{
            Dobavljac d=((TabelaDobavljac)tblDobavljac.getModel()).getSelectedObject(tblDobavljac.getSelectedRow());
            FormaDobavljacDodaj fdd=new FormaDobavljacDodaj(this,true,d,"UPDATE");
            fdd.setVisible(true);
        } 
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if(tblDobavljac.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Potrebno je da izaberete dobavljaca kog zelite da obrisete", "Greska!", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                Dobavljac d=((TabelaDobavljac)tblDobavljac.getModel()).getSelectedObject(tblDobavljac.getSelectedRow());
                Kontroler.getInstanca().delete(d);
                JOptionPane.showMessageDialog(this, "Uspesno ste obrisali dobavljaca!");
                refreshTbl();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greska prilikom brisanja dobavljaca", "Greska!", JOptionPane.ERROR_MESSAGE);
            } 
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaDobavljac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaDobavljac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaDobavljac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaDobavljac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaDobavljac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDobavljac;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        try {
            List<Dobavljac> listaDobavljaca=Kontroler.getInstanca().listaDobavljaca();
            TabelaDobavljac tblDob=new TabelaDobavljac(listaDobavljaca);
            tblDobavljac.setModel(tblDob);
        } catch (Exception ex) {
            Logger.getLogger(FormaArtikal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void refreshTbl(){
        List<Dobavljac> shownD=loadObjects();
        TabelaDobavljac tbl=(TabelaDobavljac) tblDobavljac.getModel();
        tbl.setList(shownD);
        tbl.fireTableDataChanged();
    }

    private List<Dobavljac> loadObjects() {
        try {
            return Kontroler.getInstanca().listaDobavljaca();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }
}
