/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logika.Kontroler;
import model.Prijemnica;
import tabele.TabelaPrijemnica;

/**
 *
 * @author Ana
 */
public class FormaPrijemnica extends javax.swing.JFrame {

    /**
     * Creates new form FormaPrijemnica
     */
    public FormaPrijemnica() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrijemnica = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnStavke = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prijemnica");

        tblPrijemnica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrijemnica);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnStavke.setText("Pregled stavki prijemnice");
        btnStavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStavkeActionPerformed(evt);
            }
        });

        jButton1.setText("Ponovo ucitaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addGap(87, 87, 87)
                        .addComponent(btnIzmeni)
                        .addGap(95, 95, 95)
                        .addComponent(btnObrisi)
                        .addGap(113, 113, 113)
                        .addComponent(btnStavke)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi)
                    .addComponent(btnStavke)
                    .addComponent(jButton1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try {
            List<Prijemnica> listaPrij=Kontroler.getInstanca().listaPrijemnica();
            
            int brojPrijemnice=1;
            for (Prijemnica pr : listaPrij) {
                brojPrijemnice=Integer.max(1, pr.getBrojPrijemnice());
            }
            
            
            
            Prijemnica p=new Prijemnica();
            FormaPrijemnicaDodaj fpd=new FormaPrijemnicaDodaj(this,true,p,"INSERT",brojPrijemnice);
            fpd.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FormaZapisnikOSortiranju.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if(tblPrijemnica.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Potrebno je da izaberete prijemnicu koju zelite da izmenite", "Greska!", JOptionPane.ERROR_MESSAGE);
        }else{
            Prijemnica p=((TabelaPrijemnica)tblPrijemnica.getModel()).getSelectedObject(tblPrijemnica.getSelectedRow());
            FormaPrijemnicaDodaj fpd=new FormaPrijemnicaDodaj(this,true,p,"UPDATE",0);
            fpd.setVisible(true);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if(tblPrijemnica.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Potrebno je da izaberete prijemnicu koju zelite da obrisete", "Greska!", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                Prijemnica p=((TabelaPrijemnica)tblPrijemnica.getModel()).getSelectedObject(tblPrijemnica.getSelectedRow());
                Kontroler.getInstanca().delete(p);
                JOptionPane.showMessageDialog(this, "Uspesno ste obrisali prijemnicu!");
                refreshTbl();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greska prilikom brisanja prijemnice", "Greska!", JOptionPane.ERROR_MESSAGE);
            } 
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnStavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStavkeActionPerformed
        if(tblPrijemnica.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Potrebno je da izaberete prijemnicu za koju zelite da vidite stavke", "Greska!", JOptionPane.ERROR_MESSAGE);
        }else{
            Prijemnica p=((TabelaPrijemnica)tblPrijemnica.getModel()).getSelectedObject(tblPrijemnica.getSelectedRow());
            FormaStavkaPrijemnice fsp=new FormaStavkaPrijemnice(p);
            fsp.setVisible(true);
            
        }
    }//GEN-LAST:event_btnStavkeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        refreshTbl();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPrijemnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPrijemnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPrijemnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPrijemnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaPrijemnica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnStavke;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrijemnica;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        try {
            List<Prijemnica> listaPrijemnica=Kontroler.getInstanca().listaPrijemnica();
            TabelaPrijemnica tblP=new TabelaPrijemnica(listaPrijemnica);
            tblPrijemnica.setModel(tblP);
        } catch (Exception ex) {
            Logger.getLogger(FormaArtikal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void refreshTbl(){
        List<Prijemnica> shownP=loadObjects();
        TabelaPrijemnica tbl=(TabelaPrijemnica) tblPrijemnica.getModel();
        tbl.setList(shownP);
        tbl.fireTableDataChanged();
    }

    private List<Prijemnica> loadObjects() {
        try {
            return Kontroler.getInstanca().listaPrijemnica();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }
}
