/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logika.Kontroler;
import model.Artikal;
import model.Prijemnica;
import model.StavkaPrijemnice;

/**
 *
 * @author Ana
 */
public class FormaStavkaPrijemniceDodaj extends javax.swing.JFrame {

    /**
     * Creates new form FormaStavkaPrijemniceDodaj
     */
    FormaStavkaPrijemnice parent;
    StavkaPrijemnice sp;
    String operacija;
    Prijemnica p;
    int brojStavke;
    public FormaStavkaPrijemniceDodaj(FormaStavkaPrijemnice parent, boolean modal, StavkaPrijemnice sp, String operacija, Prijemnica p, int brojStavke) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.parent=parent;
        this.sp=sp;
        this.operacija=operacija;
        this.p=p;
        this.brojStavke=brojStavke;
        if(operacija.equals("UPDATE")){
            podesiPolja(sp);
            txtPrijemnica.setText(String.valueOf(sp.getPrijemnica().getBrojPrijemnice()));
            txtPrijemnica.setEnabled(false);
            
            txtRedniBroj.setEnabled(false);
        }else if(operacija.equals("INSERT")){
            txtPrijemnica.setText(String.valueOf(p.getBrojPrijemnice()));
            txtPrijemnica.setEnabled(false);
            int brSt=brojStavke+1;
            txtRedniBroj.setText(String.valueOf(brSt));
            txtRedniBroj.setEnabled(false);
        }
        popuniCmb(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrijemnica = new javax.swing.JTextField();
        txtRedniBroj = new javax.swing.JTextField();
        txtKolicina = new javax.swing.JTextField();
        cmbArtikal = new javax.swing.JComboBox();
        btnSacuvaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stavka prijemnice");

        jLabel2.setText("Redni broj:");

        jLabel3.setText("Kolicina:");

        jLabel5.setText("Artikal:");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel1.setText("Prijemnica:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSacuvaj)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrijemnica, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                                    .addComponent(txtRedniBroj)
                                    .addComponent(txtKolicina))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(cmbArtikal, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPrijemnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRedniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cmbArtikal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSacuvaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            if(this.operacija.equals("INSERT")){
                this.insert();

            }else if(this.operacija.equals("UPDATE")){
                this.update();

            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaStavkaPrijemniceDodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaStavkaPrijemniceDodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaStavkaPrijemniceDodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaStavkaPrijemniceDodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormaStavkaPrijemniceDodaj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbArtikal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtPrijemnica;
    private javax.swing.JTextField txtRedniBroj;
    // End of variables declaration//GEN-END:variables

    private void podesiPolja(StavkaPrijemnice sp) {
        txtKolicina.setText(String.valueOf(sp.getKolicina()));
        cmbArtikal.setSelectedItem(sp.getArtikal());
        txtRedniBroj.setText(String.valueOf(sp.getRedniBroj()));
    }

    private void popuniCmb() {
        try {
            cmbArtikal.removeAllItems();
            List<Artikal> listaArt=Kontroler.getInstanca().listaArtikala();
            for (Artikal a : listaArt) {
                cmbArtikal.addItem(a);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            ex.getMessage();
        }
    }

    private void insert() throws Exception {
        if(txtKolicina.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Kolicina je obavezno polje!");
            return;
        }
        String redniBroj=txtRedniBroj.getText();
        int rb=Integer.parseInt(redniBroj);
        
        String kolicina=txtKolicina.getText();
        double kol=Double.parseDouble(kolicina);
        
        Artikal art=(Artikal) cmbArtikal.getSelectedItem();
        
        StavkaPrijemnice stp=new StavkaPrijemnice(p, rb, kol, art);
        Kontroler.getInstanca().insertWithAutoincrement(stp);
        JOptionPane.showMessageDialog(this, "Stavka prijemnice je uspesno dodata");
        
        this.dispose();
        parent.dispose();
        new FormaStavkaPrijemnice(p).setVisible(true);
        
        
    }

    private void update() throws Exception {
        if(txtKolicina.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Kolicina je obavezno polje!");
            return;
        }
        String redniBroj=txtRedniBroj.getText();
        int rb=Integer.parseInt(redniBroj);
        
        String kolicina=txtKolicina.getText();
        double kol=Double.parseDouble(kolicina);
        
        Artikal art=(Artikal) cmbArtikal.getSelectedItem();
        
        StavkaPrijemnice stp=new StavkaPrijemnice(p, rb, kol, art);
        Kontroler.getInstanca().update(stp);
        JOptionPane.showMessageDialog(this, "Stavka zapisnika prijemnice je uspesno izmenjena");
        
        this.dispose();
        parent.dispose();
        new FormaStavkaPrijemnice(p).setVisible(true);
        
        
    }
}
