/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logika.Kontroler;
import model.Knjizno_Zaduzenje;
import tabele.TabelaKnjiznoZaduzenje;

/**
 *
 * @author Ana
 */
public class FormaKnjiznoZaduzenje extends javax.swing.JFrame {

    /**
     * Creates new form FormaKnjiznoZaduzenje
     */
    public FormaKnjiznoZaduzenje() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKnjZad = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Knjizno zaduzenje");

        tblKnjZad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKnjZad);

        btnDodaj.setText("Dodaj zaduzenje");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni zaduzenje");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi zaduzenje");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jButton1.setText("Pregled stavki zaduzenja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ponovo ucitaj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addGap(122, 122, 122)
                        .addComponent(btnIzmeni)
                        .addGap(103, 103, 103)
                        .addComponent(btnObrisi)
                        .addGap(84, 84, 84)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        
        try {
            List<Knjizno_Zaduzenje> listaKZ=Kontroler.getInstanca().listaKnjiznihZaduzenja();
            
            Knjizno_Zaduzenje kz=new Knjizno_Zaduzenje();
            FormaKnjiznoZaduzenjeDodaj fkzd=new FormaKnjiznoZaduzenjeDodaj(this,true,kz,"INSERT",listaKZ);
            fkzd.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FormaKnjiznoZaduzenje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if(tblKnjZad.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Potrebno je da izaberete knjizno zaduzenje koje zelite da izmenite", "Greska!", JOptionPane.ERROR_MESSAGE);
        }else{
            
            try {
                List<Knjizno_Zaduzenje> listaKZ=Kontroler.getInstanca().listaKnjiznihZaduzenja();
                
                Knjizno_Zaduzenje kz=((TabelaKnjiznoZaduzenje)tblKnjZad.getModel()).getSelectedObject(tblKnjZad.getSelectedRow());
                FormaKnjiznoZaduzenjeDodaj fkzd=new FormaKnjiznoZaduzenjeDodaj(this,true,kz,"UPDATE",listaKZ);
                fkzd.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FormaKnjiznoZaduzenje.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if(tblKnjZad.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Potrebno je da izaberete knjizno zaduzenje koje zelite da obrisete", "Greska!", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                Knjizno_Zaduzenje kz=((TabelaKnjiznoZaduzenje)tblKnjZad.getModel()).getSelectedObject(tblKnjZad.getSelectedRow());
                Kontroler.getInstanca().delete(kz);
                JOptionPane.showMessageDialog(this, "Uspesno ste obrisali knjizno zaduzenje!");
                refreshTbl();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greska prilikom brisanja knjiznog zaduzenja", "Greska!", JOptionPane.ERROR_MESSAGE);
            } 
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tblKnjZad.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Potrebno je da izaberete knjizno zaduzenje za koje zelite da vidite stavke", "Greska!", JOptionPane.ERROR_MESSAGE);
        }else{
            Knjizno_Zaduzenje kz=((TabelaKnjiznoZaduzenje)tblKnjZad.getModel()).getSelectedObject(tblKnjZad.getSelectedRow());
            FormaStavkaKnjiznogZaduzenja fskz=new FormaStavkaKnjiznogZaduzenja(kz);
            fskz.setVisible(true);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        refreshTbl();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaKnjiznoZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaKnjiznoZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaKnjiznoZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaKnjiznoZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaKnjiznoZaduzenje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKnjZad;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        try {
            List<Knjizno_Zaduzenje> listaZaduzenja=Kontroler.getInstanca().listaKnjiznihZaduzenja();
            TabelaKnjiznoZaduzenje tblKZ=new TabelaKnjiznoZaduzenje(listaZaduzenja);
            tblKnjZad.setModel(tblKZ);
        } catch (Exception ex) {
            Logger.getLogger(FormaArtikal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void refreshTbl(){
        List<Knjizno_Zaduzenje> shownKz=loadObjects();
        TabelaKnjiznoZaduzenje tbl=(TabelaKnjiznoZaduzenje) tblKnjZad.getModel();
        tbl.setList(shownKz);
        tbl.fireTableDataChanged();
    }

    private List<Knjizno_Zaduzenje> loadObjects() {
        try {
            return Kontroler.getInstanca().listaKnjiznihZaduzenja();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }
}
