/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logika.Kontroler;
import model.Dobavljac;
import model.Kupac;
import model.Ugovor_o_Saradnji;

/**
 *
 * @author Ana
 */
public class FormaUgovorOSaradnjiDodaj extends javax.swing.JFrame {

    /**
     * Creates new form FormaUgovorOSaradnjiDodaj
     */
    Ugovor_o_Saradnji uos;
    String operacija;
    int brojUgovora;
    public FormaUgovorOSaradnjiDodaj(Ugovor_o_Saradnji uos, String operacija,int brojUgovora) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.uos=uos;
        this.operacija=operacija;
        this.brojUgovora=brojUgovora;
        if(operacija.equals("UPDATE")){
            podesiPolja(uos);
        }
        popuniCmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbDobavljac = new javax.swing.JComboBox();
        cmbKupac = new javax.swing.JComboBox();
        txtDatum = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ugovor o saradnji");

        jLabel1.setText("Dobavljac:");

        jLabel2.setText("Kupac:");

        jLabel3.setText("Datum zakljucivanja:");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvaj)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDobavljac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbKupac, 0, 398, Short.MAX_VALUE)
                            .addComponent(txtDatum))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbDobavljac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSacuvaj)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            if(this.operacija.equals("INSERT")){
                this.insert();
                
            }else if(this.operacija.equals("UPDATE")){
                this.update();
                
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaUgovorOSaradnjiDodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaUgovorOSaradnjiDodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaUgovorOSaradnjiDodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaUgovorOSaradnjiDodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormaUgovorOSaradnjiDodaj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbDobavljac;
    private javax.swing.JComboBox cmbKupac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDatum;
    // End of variables declaration//GEN-END:variables

    private void podesiPolja(Ugovor_o_Saradnji uos) {
        this.cmbDobavljac.setSelectedItem(uos.getDobavljac());
        this.cmbDobavljac.setSelectedItem(uos.getKupac());
        this.txtDatum.setText(String.valueOf(uos.getDatumZakljucivanja()));
    }

    private void popuniCmb() {
        try {
            cmbDobavljac.removeAllItems();
            List<Dobavljac> listaDobavljaca=Kontroler.getInstanca().listaDobavljaca();
            for (Dobavljac dobavljac : listaDobavljaca) {
                cmbDobavljac.addItem(dobavljac);
            }
            
            cmbKupac.removeAllItems();
            List<Kupac> listaKupaca=Kontroler.getInstanca().listaKupaca();
            for (Kupac kupac : listaKupaca) {
                cmbKupac.addItem(kupac);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            ex.getMessage();
        }
    }

    private void insert() throws Exception {
        if(txtDatum.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Datum zakljucivanja je obavezno polje!");
            return;
        }
        
        Dobavljac d=(Dobavljac) cmbDobavljac.getSelectedItem();
        Kupac k=(Kupac) cmbKupac.getSelectedItem();
        
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String dza=txtDatum.getText();
        Date dtmZaklj=new Date();
        try {
            dtmZaklj=sdf.parse(dza);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Greska pri parsiranju datuma zakljucivanja ugovora o saradnji! Datum mora biti u formatu yyyy-MM-dd.");
        }
        
        int brUg=brojUgovora+1;
        
        Ugovor_o_Saradnji ugo=new Ugovor_o_Saradnji(brUg,dtmZaklj, d, k);
        Kontroler.getInstanca().insertWithAutoincrement(ugo);
        JOptionPane.showMessageDialog(this, "Ugovor o saradnji je uspesno dodat");
        this.setVisible(false);
        dispose();
        FormaUgovorOSaradnji fus=new FormaUgovorOSaradnji();
        fus.setVisible(true);
    }

    private void update() throws Exception {
        if(txtDatum.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Datum zakljucivanja je obavezno polje!");
            return;
        }
        
        Dobavljac d=(Dobavljac) cmbDobavljac.getSelectedItem();
        Kupac k=(Kupac) cmbKupac.getSelectedItem();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String dz=txtDatum.getText();
        Date dtmZak=new Date();
        try {
            dtmZak=sdf.parse(dz);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Greska pri parsiranju datuma zakljucivanja ugovora o saradnji! Datum mora biti u formatu yyyy-MM-dd.");
        }
        
        Ugovor_o_Saradnji ug=new Ugovor_o_Saradnji(uos.getUgovorID(), dtmZak, d, k);
        Kontroler.getInstanca().update(ug);
        JOptionPane.showMessageDialog(this, "Ugovor o saradnji je uspesno izmenjen");
        this.setVisible(false);
        dispose();
        FormaUgovorOSaradnji fus=new FormaUgovorOSaradnji();
        fus.setVisible(true);
    }
}
