/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import javax.swing.JFrame;

/**
 *
 * @author Ana
 */
public class MainForma extends javax.swing.JFrame {

    /**
     * Creates new form MainForma
     */
    public MainForma() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiArtikal = new javax.swing.JMenuItem();
        jmiCenaArtikla = new javax.swing.JMenuItem();
        jmiJM = new javax.swing.JMenuItem();
        Clan = new javax.swing.JMenu();
        jmiZakon = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiKupac = new javax.swing.JMenuItem();
        jmiDobavljac = new javax.swing.JMenuItem();
        jmiUgovorOSaradnji = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiRadnik = new javax.swing.JMenuItem();
        jmiZapisnik = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiKnjZad = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiPrijemnica = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reciklaza sekundarnih sirovina");
        setName(""); // NOI18N

        jMenu1.setText("Artikal");

        jmiArtikal.setText("Artikal");
        jmiArtikal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiArtikalActionPerformed(evt);
            }
        });
        jMenu1.add(jmiArtikal);

        jmiCenaArtikla.setText("Cena artikla");
        jmiCenaArtikla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCenaArtiklaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCenaArtikla);

        jmiJM.setText("Jedinica mere");
        jmiJM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiJMActionPerformed(evt);
            }
        });
        jMenu1.add(jmiJM);

        jMenuBar1.add(jMenu1);

        Clan.setText("Zakon");

        jmiZakon.setText("Zakon");
        jmiZakon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiZakonActionPerformed(evt);
            }
        });
        Clan.add(jmiZakon);

        jMenuBar1.add(Clan);

        jMenu2.setText("Ugovor ");

        jmiKupac.setText("Kupac");
        jmiKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKupacActionPerformed(evt);
            }
        });
        jMenu2.add(jmiKupac);

        jmiDobavljac.setText("Dobavljac");
        jmiDobavljac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDobavljacActionPerformed(evt);
            }
        });
        jMenu2.add(jmiDobavljac);

        jmiUgovorOSaradnji.setText("Ugovor o saradnji");
        jmiUgovorOSaradnji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUgovorOSaradnjiActionPerformed(evt);
            }
        });
        jMenu2.add(jmiUgovorOSaradnji);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Zapisnik");

        jmiRadnik.setText("Radnik");
        jmiRadnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRadnikActionPerformed(evt);
            }
        });
        jMenu3.add(jmiRadnik);

        jmiZapisnik.setText("Zapisnik o sortiranju");
        jmiZapisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiZapisnikActionPerformed(evt);
            }
        });
        jMenu3.add(jmiZapisnik);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Knjizno zaduzenje");

        jmiKnjZad.setText("Knjizno zaduzenje");
        jmiKnjZad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKnjZadActionPerformed(evt);
            }
        });
        jMenu4.add(jmiKnjZad);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Prijemnica");

        jmiPrijemnica.setText("Prijemnica");
        jmiPrijemnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrijemnicaActionPerformed(evt);
            }
        });
        jMenu5.add(jmiPrijemnica);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiArtikalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiArtikalActionPerformed
        FormaArtikal fa=new FormaArtikal();
        fa.setVisible(true);
    }//GEN-LAST:event_jmiArtikalActionPerformed

    private void jmiCenaArtiklaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCenaArtiklaActionPerformed
        FormaCenaArtikla fca=new FormaCenaArtikla();
        fca.setVisible(true);
    }//GEN-LAST:event_jmiCenaArtiklaActionPerformed

    private void jmiZakonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiZakonActionPerformed
        FormaZakon fz=new FormaZakon();
        fz.setVisible(true);
    }//GEN-LAST:event_jmiZakonActionPerformed

    private void jmiKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKupacActionPerformed
        FormaKupac fk=new FormaKupac();
        fk.setVisible(true);
    }//GEN-LAST:event_jmiKupacActionPerformed

    private void jmiDobavljacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDobavljacActionPerformed
        FormaDobavljac fd=new FormaDobavljac();
        fd.setVisible(true);
    }//GEN-LAST:event_jmiDobavljacActionPerformed

    private void jmiUgovorOSaradnjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUgovorOSaradnjiActionPerformed
        FormaUgovorOSaradnji fuos=new FormaUgovorOSaradnji();
        fuos.setVisible(true);
    }//GEN-LAST:event_jmiUgovorOSaradnjiActionPerformed

    private void jmiZapisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiZapisnikActionPerformed
        FormaZapisnikOSortiranju fzap=new FormaZapisnikOSortiranju();
        fzap.setVisible(true);
    }//GEN-LAST:event_jmiZapisnikActionPerformed

    private void jmiRadnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRadnikActionPerformed
        FormaRadnik fr=new FormaRadnik();
        fr.setVisible(true);
    }//GEN-LAST:event_jmiRadnikActionPerformed

    private void jmiKnjZadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKnjZadActionPerformed
        FormaKnjiznoZaduzenje fkz=new FormaKnjiznoZaduzenje();
        fkz.setVisible(true);
    }//GEN-LAST:event_jmiKnjZadActionPerformed

    private void jmiJMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJMActionPerformed
        FormaJedinicaMere fjm=new FormaJedinicaMere();
        fjm.setVisible(true);
    }//GEN-LAST:event_jmiJMActionPerformed

    private void jmiPrijemnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrijemnicaActionPerformed
        FormaPrijemnica fp=new FormaPrijemnica();
        fp.setVisible(true);
    }//GEN-LAST:event_jmiPrijemnicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Clan;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiArtikal;
    private javax.swing.JMenuItem jmiCenaArtikla;
    private javax.swing.JMenuItem jmiDobavljac;
    private javax.swing.JMenuItem jmiJM;
    private javax.swing.JMenuItem jmiKnjZad;
    private javax.swing.JMenuItem jmiKupac;
    private javax.swing.JMenuItem jmiPrijemnica;
    private javax.swing.JMenuItem jmiRadnik;
    private javax.swing.JMenuItem jmiUgovorOSaradnji;
    private javax.swing.JMenuItem jmiZakon;
    private javax.swing.JMenuItem jmiZapisnik;
    // End of variables declaration//GEN-END:variables
}
